In [ ]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.Tensor(5, 3)
print(x)


-4.9350e+11  4.5828e-41 -4.9350e+11
 4.5828e-41  5.2839e-11  1.1260e+24
 1.8888e+31  4.7414e+16  1.4917e-07
 8.0221e+17  1.3556e-19  1.8567e-01
 5.6417e-11  6.7421e+22  7.0369e+28
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)


 0.9956  0.3555  0.2931
 0.1706  0.6405  0.4427
 0.1969  0.9099  0.1098
 0.1602  0.6229  0.0832
 0.2417  0.2549  0.3615
[torch.FloatTensor of size 5x3]



Get its size:



In [5]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [6]:
y = torch.rand(5, 3)
print(x + y)


 1.5676  1.0472  0.6487
 0.9756  1.3896  1.4151
 0.9354  1.7762  0.6727
 0.1906  1.4831  0.9824
 0.5535  0.7556  0.6618
[torch.FloatTensor of size 5x3]



Addition: syntax 2



In [7]:
print(torch.add(x, y))


 1.5676  1.0472  0.6487
 0.9756  1.3896  1.4151
 0.9354  1.7762  0.6727
 0.1906  1.4831  0.9824
 0.5535  0.7556  0.6618
[torch.FloatTensor of size 5x3]



Addition: providing an output tensor as argument



In [8]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.5676  1.0472  0.6487
 0.9756  1.3896  1.4151
 0.9354  1.7762  0.6727
 0.1906  1.4831  0.9824
 0.5535  0.7556  0.6618
[torch.FloatTensor of size 5x3]



Addition: in-place



In [9]:
# adds x to y
y.add_(x)
print(y)


 1.5676  1.0472  0.6487
 0.9756  1.3896  1.4151
 0.9354  1.7762  0.6727
 0.1906  1.4831  0.9824
 0.5535  0.7556  0.6618
[torch.FloatTensor of size 5x3]



<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [10]:
print(x[:, 1])


 0.3555
 0.6405
 0.9099
 0.6229
 0.2549
[torch.FloatTensor of size 5]



Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
x.view?

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [13]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [14]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.



In [15]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto GPU using the ``.cuda`` method.



In [17]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

In [18]:
x.cuda()

AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx